FROM python:3.13-slim

WORKDIR /app

COPY requirements_app.txt .

RUN pip install --no-cache-dir -r requirements_app.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]